---
title: "Individual Assignment 5"
author: "Maisie Prestridge"
date: "05/10/2026"
format: pdf
---

# 1. Set up

## Packages

```{r}

# general use and cleaning
library(tidyverse)
library(here)
library(janitor)
library(snakecase)

# wrap axis labels
library(scales)

# reading .xlsx files 
library(readxl)

# visualise missing data 
library(naniar)

# arrange plots
library(patchwork)
```

## Data

```{r}
#| label: data

# taxonomic information
taxon_list <- read_csv(here("data", "taxon_list.csv")) 

# aquatic invertebrates
aq_ins <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                    sheet = "Aquatic Insects") 

# site information
sites <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                   sheet = "sites")

# water quality
water_quality <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                           sheet = "Water Quality",
                           na = c("", "n/a", "N/A", "over", "173+"))

```

